GET localhost:9091/api/pages/mp/organization/data?page=0&size=2&name=C
#Content-Type: application/json
#
#{
#  "roleName": "普通管理员",
#  "account": "张三",
#  "pageNum": 0,
#  "pageSize": 2
#}

### HELLOWORLD
POST localhost:9091/collection
Content-Type: application/json
Accept: application/xml

{
  "roleName": "1",
  "account": "1",
  "pageNum": 0,
  "pageSize": 2
}